name: Generate and Update Spofity SVG

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Spotify SVG
        run: |
          mkdir -p dist
          curl -L "https://spotify-github-profile.kittinanx.com/api/view?uid=pjyifjjapvah0yoy2zvd8vx0v&cover_image=true&theme=default&show_offline=false&background_color=0d1117&interchange=true&bar_color=53b14f&bar_color_cover=true" -o dist/spotify.svg

      - name: Push Spotify SVG to the spotify branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: spotify
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Inline SVG Contents
        run: |
          mkdir -p temp
          MAIN_SVG="html-wrapper.svg" 
          TEMP_FILE="temp/updated.svg"

          # Read the current SVG into memory
          content=$(cat "$MAIN_SVG")

          # Function to replace content between markers
          replace_between_markers() {
            local start_marker="$1"
            local end_marker="$2"
            local new_content_file="$3"

            # Escape slashes and newlines for safe replacement
            new_content=$(sed ':a;N;$!ba;s/\n/\\n/g' "$new_content_file")

            # Use awk instead of sed to replace content between markers safely
            content=$(awk -v start="$start_marker" -v end="$end_marker" -v new_content="$new_content" '
              {
                if ($0 ~ start) { print; print new_content; inside=1; next }
                if ($0 ~ end) { inside=0 }
                if (!inside) print
              }
            ' <<< "$content")
          }

          # Apply replacements
          replace_between_markers "<!-- INLINE SPOTIFY START -->" "<!-- INLINE SPOTIFY END -->" "dist/spotify.svg"

          # Write the final modified content back to the file
          echo "$content" > "$MAIN_SVG"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add html-wrapper.svg
          git commit -m "Auto-update SVG with inlined external content" || exit 0
          git pull --rebase origin main
          git push origin main
